site_name: ai-stack
site_description: "Notes, tips, ML/AI projects, and LLM apps"
site_url: https://afizs.github.io/ai-stack/
repo_url: https://github.com/afizs/ai-stack
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - search.highlight
    - content.action.edit        # adds “Edit this page” links
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - codeinclude                  # optional; include code directly into docs
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Notes: 10-notes/README.md
  - Tips: 20-tips/README.md
  - Snippets: 30-snippets/README.md
  - Projects:
      - Iris Classifier: projects/iris-classifier.md
      - Agentic RAG: projects/agentic-rag.md
  - Machine Learning:
      - Model Zoo: 50-ml/model-zoo.md
  - AI: 60-ai/experiments.md
  - LLM:
      - Concepts: 70-llm/docs/llm-concepts.md
      - Prompt Patterns: 70-llm/prompts/patterns.md
      - Apps: 70-llm/apps/streamlit-chat/README.md
  - Datasets: 80-datasets/samples.md
  - Resources:
      - Papers: 90-resources/papers.md
      - Bookmarks: 90-resources/bookmarks.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/afizs/ai-stack
