site_name: ai-stack
site_description: "Notes, tips, ML/AI projects, and LLM apps"
site_url: https://afizs.github.io/ai-stack/
repo_url: https://github.com/afizs/ai-stack
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
  - codeinclude                  # optional; include code directly into docs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false  # Disable showing source code
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
nav:
  - Home: index.md
  # - Notes: 10-notes/README.md
  # - Tips: 20-tips/README.md
  # - Snippets: 30-snippets/README.md
  - Projects:
      - Iris Classifier: projects/iris-classifier.md
      - Mini ChatGPT: projects/mini-chatgpt.md
      # - Agentic RAG: projects/agentic-rag.md
  # - Machine Learning:
  #     - Model Zoo: 50-ml/model-zoo.md
  # - AI: 60-ai/experiments.md
  # - LLM:
  #     - Concepts: 70-llm/docs/llm-concepts.md
  #     - Prompt Patterns: 70-llm/prompts/patterns.md
  #     - Apps: 70-llm/apps/streamlit-chat/README.md
  # - Datasets: 80-datasets/samples.md
  # - Resources:
  #     - Papers: 90-resources/papers.md
  #     - Bookmarks: 90-resources/bookmarks.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/afizs/ai-stack
